### ISSUE TITLE
Simulating trees with multi-trait-dependent speciation and extinction

### ISSUE THREAD

**Issue by LRombaut** [TGuillerme/treats#14]
I would like to generate trees where speciation and extinction rates depend on multiple traits at once and it's not clear to me from the manual how this would be done in dads. There is also the issue of accounting for evolution of traits happening along branches that continuously changes the speciation and extinction rates- something not accounted for if you only consider the character states at nodes. I propose the following algorithm for doing this based on my own attempts at writing code to do the tree simulations I want. It makes use of the 'memoryless' property of the exponential distribution, namely that the distribution of waiting times to a speciation or extinction event is independent of how much time has already elapsed. 

1. Let the rates of speciation (lambda(...)) and extinction (mu(...)) per lineage per unit time be any arbitrary functions of the traits of that lineage at any point in time. 
2. Set a small increment of time dt over which evolution of traits will be simulated 
3. Consider all lineages that are still alive at some time t=t0, and sample some random lineage
4. For this random lineage draw a waiting time to the next event from an exponential distribution with parameter (lambda+mu)*dt. 
   a. If the waiting time exceeds dt: The lineage neither speciates nor goes extinct. Simulate trait evolution from t=t0 up to t0 + dt. Re-evaluate lambda and mu as functions of the updated character states, then do step 4 again. 
  b. If the waiting time is less than dt: The lineage either speciates or goes extinct. To decide which it is make a random draw from a uniform distribution and check if it is more or less than lambda/(lambda+mu). If it goes extinct, go to step 3. If it speciates select one of the daughter lineages and go back to step 4. 
5. The stopping condition is if a lineage reaches t=tmax, in which case go back to step 3 and sample another random lineage OR if a certain number of tips is desired the tree can be pruned

**Comment by TGuillerme** [comment]
I've now added an illustrated example for this bit in the updated version of the manual
